import { Platform, StyleSheet } from 'react-native';

export const newEntryStyles = StyleSheet.create({
    background: {
        flex: 1,
    },
    container: {
        flex: 1,
        paddingHorizontal: 20,
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
    },
    headerSection: {
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        borderRadius: 20,
        paddingVertical: 20,
        paddingHorizontal: 24,
        shadowColor: '#6a66a3',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 5,
        marginBottom: 20,
    },
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    titleEmoji: {
        fontSize: 32,
        marginRight: 10,
    },
    title: {
        fontSize: 32,
        fontWeight: '800',
        color: '#2d1b69',
        textAlign: 'center',
        letterSpacing: 0.5,
        textShadowColor: 'rgba(106, 102, 163, 0.3)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
    },
    subtitle: {
        fontSize: 16,
        color: '#6a4c93',
        textAlign: 'center',
        fontWeight: '600',
    },
    scrollContent: {
        flexGrow: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingBottom: 20,
    },
    inputContainer: {
        backgroundColor: '#6a66a3',
        borderRadius: 16,
        padding: 20,
        minHeight: 160,
        marginBottom: 30,
        shadowColor: '#6a66a3',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 4,
        alignSelf: 'stretch',
    },
    input: {
        color: '#fff',
        fontSize: 16,
        textAlignVertical: 'top',
        minHeight: 120,
        fontWeight: '500',
    },
    buttonContainer: {
        gap: 15,
        alignSelf: 'stretch',
    },
    saveButton: {
        backgroundColor: '#6a66a3',
        paddingVertical: 14,
        paddingHorizontal: 32,
        borderRadius: 16,
        shadowColor: '#6a66a3',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 4,
        alignItems: 'center',
    },
    saveButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
    },
    backButton: {
        backgroundColor: '#b5838d',
        paddingVertical: 14,
        paddingHorizontal: 32,
        borderRadius: 16,
        shadowColor: '#b5838d',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 4,
        alignItems: 'center',
    },
    backButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
    },
});

export const journalScreenStyles = StyleSheet.create({
    background: {
        flex: 1,
    },
    container: {
        flex: 1,
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        paddingHorizontal: 20,
    },
    headerSection: {
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        borderRadius: 20,
        paddingVertical: 20,
        paddingHorizontal: 24,
        shadowColor: '#6a66a3',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 5,
        marginBottom: 20,
    },
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    titleEmoji: {
        fontSize: 28,
        marginRight: 10,
    },
    title: {
        fontSize: 32,
        fontWeight: '800',
        color: '#2d1b69',
        textAlign: 'center',
        letterSpacing: 0.5,
        textShadowColor: 'rgba(106, 102, 163, 0.3)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
    },
    contentSection: {
        flex: 1,
    },
    listContentContainer: {
        paddingBottom: 20,
    },
    entryBox: {
        backgroundColor: '#f2e9f4',
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
    },
    entryDate: {
        fontSize: 14,
        fontWeight: '600',
        color: '#6a4c93',
        marginBottom: 8,
    },
    entryText: {
        fontSize: 16,
        color: '#333',
        lineHeight: 22,
    },
    floatingAddButton: {
        position: 'absolute',
        bottom: 90,
        alignSelf: 'center',
        backgroundColor: '#6a66a3',
        width: 60,
        height: 60,
        borderRadius: 30,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#6a66a3',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
    addButtonText: {
        color: '#fff',
        fontSize: 28,
        fontWeight: 'bold',
    },
    emptyStateContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    emptyStateText: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#6a66a3',
        marginBottom: 8,
        textAlign: 'center',
    },
    emptyStateSubtext: {
        fontSize: 16,
        color: '#6a66a3',
        textAlign: 'center',
        opacity: 0.8,
    },
});
