import { Platform, StyleSheet } from 'react-native';

export const homeScreenStyles = StyleSheet.create({
    background: {
        flex: 1,
    },
    container: {
        flex: 1,
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        paddingHorizontal: 20,
        alignItems: 'center',
        paddingBottom: 20,
    },
    scrollContent: {
        flexGrow: 1,
        alignItems: 'center',
        width: '100%',
    },
    headerSection: {
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        borderRadius: 20,
        paddingVertical: 20,
        paddingHorizontal: 24,
        shadowColor: '#6a66a3',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 5,
        marginBottom: 24,
        width: '100%',
    },
    logoWrapper: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    title: {
        fontSize: 36,
        fontWeight: '800',
        color: '#2d1b69',
        marginTop: 8,
    },
    subtitle: {
        fontSize: 16,
        color: '#6a4c93',
        fontWeight: '600',
        marginTop: 4,
    },
    contentSection: {
        width: '100%',
        alignItems: 'center',
    },
    goalBox: {
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        paddingVertical: 16,
        paddingHorizontal: 20,
        borderRadius: 16,
        marginBottom: 24,
        width: '100%',
        shadowColor: '#6a66a3',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    goalText: {
        fontSize: 18,
        color: '#2d1b69',
        fontWeight: '700',
        textAlign: 'center',
    },
    moodSection: {
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        paddingVertical: 20,
        paddingHorizontal: 24,
        borderRadius: 16,
        width: '100%',
        alignItems: 'center',
        shadowColor: '#6a66a3',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    moodPrompt: {
        fontSize: 20,
        color: '#2d1b69',
        marginBottom: 16,
        fontWeight: '600',
    },
    emojiRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '80%',
        marginBottom: 16,
    },
    emoji: {
        fontSize: 48,
        opacity: 0.7,
    },
    emojiSelected: {
        opacity: 1,
        transform: [{ scale: 1.2 }],
    },
    moodLabel: {
        fontSize: 18,
        color: '#6a4c93',
        fontWeight: '600',
        marginTop: 8,
    },
});
