import { Platform, StyleSheet } from 'react-native';

export const moodGraphStyles = StyleSheet.create({
    background: {
        flex: 1,
    },
    container: {
        flex: 1,
        paddingTop: Platform.OS === 'ios' ? 60 : 40,
        paddingHorizontal: 20,
        paddingBottom: 20,
        alignItems: 'center',
    },
    scrollContent: {
        flexGrow: 1,
        width: '100%',
    },
    headerSection: {
        alignItems: 'center',
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        borderRadius: 20,
        paddingVertical: 20,
        paddingHorizontal: 24,
        shadowColor: '#6a66a3',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 5,
        marginBottom: 20,
        width: '100%',
    },
    titleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    titleEmoji: {
        fontSize: 28,
        marginRight: 10,
    },
    title: {
        fontSize: 32,
        fontWeight: '800',
        color: '#2d1b69',
        textAlign: 'center',
        letterSpacing: 0.5,
    },
    subtitle: {
        fontSize: 16,
        color: '#6a4c93',
        textAlign: 'center',
        fontWeight: '600',
    },
    rangeSelectorContainer: {
        flexDirection: 'row',
        marginBottom: 24,
        justifyContent: 'center',
        width: '100%',
    },
    rangeButton: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 16,
        marginHorizontal: 4,
        borderRadius: 12,
        backgroundColor: '#ffffffcc',
        borderWidth: 1,
        borderColor: '#6a66a3',
        alignItems: 'center',
        justifyContent: 'center',
    },
    rangeButtonSelected: {
        backgroundColor: '#6a66a3',
    },
    rangeButtonText: {
        color: '#6a66a3',
        fontWeight: 'bold',
        fontSize: 16,
    },
    rangeButtonTextSelected: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    chartWrapper: {
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 266,
        width: '100%',
    },
    loadingIndicator: {
        marginTop: 60,
    },
    noDataText: {
        fontSize: 18,
        color: '#6a4c93',
        fontWeight: '600',
        textAlign: 'center',
        marginTop: 60,
    },
    moodLegendWrapper: {
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 16,
        marginTop: 20,
        width: '100%',
        alignItems: 'center',
        shadowColor: '#6a66a3',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    moodLegendTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 6,
    },
    moodLegendRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        width: '100%',
    },
    moodLegendLabel: {
        textAlign: 'center',
        fontSize: 14,
        color: '#333',
    },
});
